### PR TITLE
Fix closing of old database

### LINKED ISSUE #7: Fix database pruning: remove epoch key from db map
**Describe the bug**

As soon as one epoch gets pruned the status endpoint call fails because it tries to access the newly pruned database.

**To Reproduce**

Steps to reproduce the behavior.

1. Remove database from database pool.
2. Get available databases from pool (for example via status endpoint call).
3. Client get's a 5xx error and error is logged.

**Expected behavior**

When removing a database from the pool it should be properly removed so that no code tries to access it later again.

**Additional context**

This is not sufficient for removing the database from the pool:

```
closeEpochStore(dp.stores[epoch], epoch)
dp.stores[epoch] = nil // not enough for removing
```

The error occurs later in:

```
for key := range dp.stores { // still has the epoch key
```

### PR DESCRIPTION
**Pull request by qubicmio**
Delete the databases epoch key properly from the map. Setting the value to null is not enough.

Closes #7

### CODE REVIEW

File: db/database_pool.go [hunk 1]
```diff
@@ -10,14 +10,16 @@ import (
...
 )
 
 type DatabasePool struct {
-	storeDir  string
-	stores    map[uint16]*PebbleStore
-	maxEpochs int
+	storeDir        string
+	stores          map[uint16]*PebbleStore
+	maxEpochs       int
+	createStoreLock sync.Mutex
```
Comment (0xluk) [inline db/database_pool.go]: `mu` as a variable should be more than enough from my pov
